# ----------------------------
# Makefile Options
# ----------------------------

NAME = SNAKE
ICON = icon.png
DESCRIPTION = "CE snake game"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
